# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RecipeGenerator' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for RecipeGenerator
  pod 'NewRelicAgent'

end

target 'RecipeGenerator-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for RecipeGenerator-tvOS

end
